channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.28.0
- assyst =0.13.0
- atomistics =0.3.6
- coverage
- defusedxml =0.7.1
- h5py =3.16.0
- matplotlib-base =3.10.9
- mendeleev =1.1.0
- mp-api =0.46.1
- numpy =2.3.5
- pandas =3.0.2
- phonopy =3.5.1
- pint =0.25.2
- pyiron_base =0.15.14
- lammpsparser =0.0.3
- vaspparser =0.0.3
- pyiron_snippets =1.2.1
- pylammpsmpi =0.3.12
- pyscal3 =3.3.2
- scikit-learn =1.8.0
- scipy =1.17.1
- seekpath =2.2.1
- spglib =2.7.0
- structuretoolkit =0.0.42
- sphinx_parser =0.1.7
- pyxtal =1.1.1
- hatchling =1.29.0
- hatch-vcs =0.5.0
