channels:
- conda-forge
dependencies:
- nbsphinx
- sphinx
- sphinx_rtd_theme
- myst-parser
- aimsgb =1.1.0
- ase =3.29.0
- assyst =0.15.0
- atomistics =0.3.8
- defusedxml =0.7.1
- h5py =3.16.0
- matplotlib-base =3.11.0
- mendeleev =1.1.0
- mp-api =0.46.4
- numpy =2.4.3
- pandas =2.3.3
- phonopy =4.3.1
- pint =0.25.2
- pyiron_base =0.15.14
- lammpsparser =0.0.7
- pyiron_snippets =1.2.1
- vaspparser =0.0.6
- pylammpsmpi =0.3.12
- pyscal3 =3.3.2
- scikit-learn =1.9.0
- scipy =1.17.1
- seekpath =2.2.1
- spglib =2.7.0
- structuretoolkit =0.0.45
- pyxtal =1.1.1
- jupyter-book =1.0.0
- sphinx_parser =0.1.9
- hatchling =1.30.1
- hatch-vcs =0.5.0
